name: 01 - hello world

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Print a greeting
        run: echo "hello Github action.."

      - name: print multiple lines
        run: |
          echo "This step runs several shell commands."
          echo "Today's runner is: $RUNNER_OS"
          echo "The repository is: $GITHUB_REPOSITORY"
           echo "This step runs several shell commands."
           echo "this is last line"
           echo "this is last line1111"
          

      
